# specify the gdml file you want to use
/MG/geometry/GDML/sourceFile %(templatepath)s/Pb.gdml

# use low energy physics list
/MG/processes/lowenergy true
/MG/manager/heprandomseed %(rnum)i

# set output schema and define file name
/MG/eventaction/rootschema G4Steps
/MG/eventaction/rootfilename %(outdir)s/Pb_%(energy)sMeV_%(rnum)s.root

# initialize MaGe
/run/initialize

# draw the geometry
#/vis/open OGLSX
#/vis/viewer/set/viewpointVector 0 1 1
#/vis/viewer/set/background white
#/vis/viewer/set/defaultColour black
#/vis/viewer/set/viewpointThetaPhi 45
#/vis/drawVolume

# a simple simulation
/MG/generator/select SPS
/gps/particle neutron
/gps/energy %(energy)s MeV
/gps/position 0 0 0
/gps/direction 0 0 1

# show the simulation
#/vis/scene/add/trajectories
/run/beamOn %(nevts)s
